name: specification
version: 0.0.1
author: Tomochika Hara <tomochikahara@gmail.com>
description: Dart implementation of the Specification pattern in Domain Driven Design.
environment:
  sdk: '>=0.4.7+1'
dev_dependencies:
  unittest: any
