name: specification
version: 0.0.1
description: Dart implementation of the Specification pattern in Domain Driven Design.
author: Tomochika Hara <tomochikahara@gmail.com>
homepage: https://github.com/tomochikahara/specification.dart
environment:
  sdk: '>=0.4.7+1'
dev_dependencies:
  unittest: any
